# Configure bors to check for our circleci job statuses
# https://bors.tech/
status = [
    "ci/circleci: api",
    "ci/circleci: web",
    "ci/circleci: e2e-lint",
    "ci/circleci: release-staging-web",
    "ci/circleci: release-staging-api",
    "ci/circleci: e2e-staging",
]
use_squash_merge = true
required_approvals = 1
delete_merged_branches = true