#!/usr/bin/env bash

set -euo pipefail

if git diff-index --quiet HEAD -- web; then
  echo "=== skipping web lint, no changes found ==="
else
  echo "=== checking web formatting ==="
  docker-compose run --rm web yarn checkstyle
  echo "=== typechecking web ==="
  docker-compose run --rm web yarn typecheck
fi

if git diff-index --quiet HEAD -- api; then
  echo "=== Skipping api lint, no changes found =="
else
  echo "=== checking api formatting ==="
  docker-compose run --rm api black -S src tests main.py --check
  echo "=== checking api style ==="
  docker-compose run --rm api flake8 src tests main.py
  echo "=== typechecking api ==="
  docker-compose run --rm api mypy src tests main.py
fi
